name: Check pre-commit rules

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  container:
    runs-on: ubuntu-latest
    container:
      image: zimkal/qemu2
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: |
          rm -rf /opt/esp/idf/components/freertos/FreeRTOS-Kernel-SMP/*
          cp -r ./FreeRTOS-Kernel/* /opt/esp/idf/components/freertos/FreeRTOS-Kernel-SMP
          . /opt/esp/idf/export.sh
          python3 /opt/esp/idf/tools/ci/ci_build_apps.py . --target esp32 -m qemu -vv --pytest-apps
          pytest --target esp32 -m qemu --embedded-services idf,qemu --build-dir=build_esp32_default
        name: Run in container
